# coding: UTF-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

regions = Region.create([
{code: 'AE', name_en: 'United Arab Emirates', name_ja: 'アラブ首長国連邦'},
{code: 'AG', name_en: 'Antigua and Barbuda', name_ja: 'アンティグア･バーブーダ'},
{code: 'AI', name_en: 'Anguilla', name_ja: 'アンギラ'},
{code: 'AL', name_en: 'Albania', name_ja: 'アルバニア'},
{code: 'AM', name_en: 'Armenia', name_ja: 'アルメニア'},
{code: 'AO', name_en: 'Angola', name_ja: 'アンゴラ'},
{code: 'AR', name_en: 'Argentina', name_ja: 'アルゼンチン'},
{code: 'AT', name_en: 'Austria', name_ja: 'オーストリア'},
{code: 'AU', name_en: 'Australia', name_ja: 'オーストラリア'},
{code: 'AZ', name_en: 'Azerbaijan', name_ja: 'アゼルバイジャン'},
{code: 'BB', name_en: 'Barbados', name_ja: 'バルバドス'},
{code: 'BE', name_en: 'Belgium', name_ja: 'ベルギー'},
{code: 'BF', name_en: 'Burkina Faso', name_ja: 'ブルキナファソ'},
{code: 'BG', name_en: 'Bulgaria', name_ja: 'ブルガリア'},
{code: 'BH', name_en: 'Bahrain', name_ja: 'バーレーン'},
{code: 'BJ', name_en: 'Benin', name_ja: 'ベナン'},
{code: 'BM', name_en: 'Bermuda', name_ja: 'バミューダ'},
{code: 'BN', name_en: 'Brunei Darussalam', name_ja: 'ブルネイ'},
{code: 'BO', name_en: 'Bolivia', name_ja: 'ボリビア'},
{code: 'BR', name_en: 'Brazil', name_ja: 'ブラジル'},
{code: 'BS', name_en: 'Bahamas', name_ja: 'バハマ'},
{code: 'BT', name_en: 'Bhutan', name_ja: 'ブータン'},
{code: 'BW', name_en: 'Botswana', name_ja: 'ボツワナ'},
{code: 'BY', name_en: 'Belarus', name_ja: 'ベラルーシ'},
{code: 'BZ', name_en: 'Belize', name_ja: 'ベリーズ'},
{code: 'CA', name_en: 'Canada', name_ja: 'カナダ'},
{code: 'CG', name_en: 'Congo, Republic of the', name_ja: 'コンゴ共和国'},
{code: 'CH', name_en: 'Switzerland', name_ja: 'スイス'},
{code: 'CL', name_en: 'Chile', name_ja: 'チリ'},
{code: 'CN', name_en: 'China', name_ja: '中国'},
{code: 'CO', name_en: 'Colombia', name_ja: 'コロンビア'},
{code: 'CR', name_en: 'Costa Rica', name_ja: 'コスタリカ'},
{code: 'CV', name_en: 'Cape Verde', name_ja: 'カーボベルデ'},
{code: 'CY', name_en: 'Cyprus', name_ja: 'キプロス'},
{code: 'CZ', name_en: 'Czech Republic', name_ja: 'チェコ共和国'},
{code: 'DE', name_en: 'Germany', name_ja: 'ドイツ'},
{code: 'DK', name_en: 'Denmark', name_ja: 'デンマーク'},
{code: 'DM', name_en: 'Dominica', name_ja: 'ドミニカ国'},
{code: 'DO', name_en: 'Dominican Republic', name_ja: 'ドミニカ共和国'},
{code: 'DZ', name_en: 'Algeria', name_ja: 'アルジェリア'},
{code: 'EC', name_en: 'Ecuador', name_ja: 'エクアドル'},
{code: 'EE', name_en: 'Estonia', name_ja: 'エストニア'},
{code: 'EG', name_en: 'Egypt', name_ja: 'エジプト'},
{code: 'ES', name_en: 'Spain', name_ja: 'スペイン'},
{code: 'FI', name_en: 'Finland', name_ja: 'フィンランド'},
{code: 'FJ', name_en: 'Fiji', name_ja: 'フィジー'},
{code: 'FM', name_en: 'Micronesia, Federated States of', name_ja: 'ミクロネシア連邦'},
{code: 'FR', name_en: 'France', name_ja: 'フランス'},
{code: 'GB', name_en: 'United Kingdom', name_ja: 'イギリス'},
{code: 'GD', name_en: 'Grenada', name_ja: 'グレナダ'},
{code: 'GH', name_en: 'Ghana', name_ja: 'ガーナ'},
{code: 'GM', name_en: 'Gambia', name_ja: 'ガンビア'},
{code: 'GR', name_en: 'Greece', name_ja: 'ギリシャ'},
{code: 'GT', name_en: 'Guatemala', name_ja: 'グアテマラ'},
{code: 'GW', name_en: 'Guinea-Bissau', name_ja: 'ギニアビサウ'},
{code: 'GY', name_en: 'Guyana', name_ja: 'ガイアナ'},
{code: 'HK', name_en: 'Hong Kong', name_ja: '香港'},
{code: 'HN', name_en: 'Honduras', name_ja: 'ホンジュラス'},
{code: 'HR', name_en: 'Croatia', name_ja: 'クロアチア'},
{code: 'HU', name_en: 'Hungary', name_ja: 'ハンガリー'},
{code: 'ID', name_en: 'Indonesia', name_ja: 'インドネシア'},
{code: 'IE', name_en: 'Ireland', name_ja: 'アイルランド'},
{code: 'IL', name_en: 'Israel', name_ja: 'イスラエル'},
{code: 'IN', name_en: 'India', name_ja: 'インド'},
{code: 'IS', name_en: 'Iceland', name_ja: 'アイスランド'},
{code: 'IT', name_en: 'Italy', name_ja: 'イタリア'},
{code: 'JM', name_en: 'Jamaica', name_ja: 'ジャマイカ'},
{code: 'JO', name_en: 'Jordan', name_ja: 'ヨルダン'},
{code: 'JP', name_en: 'Japan', name_ja: '日本'},
{code: 'KE', name_en: 'Kenya', name_ja: 'ケニア'},
{code: 'KG', name_en: 'Kyrgyzstan', name_ja: 'キルギスタン'},
{code: 'KH', name_en: 'Cambodia', name_ja: 'カンボジア'},
{code: 'KN', name_en: 'St. Kitts and Nevis', name_ja: 'セントクリストファー・ネイビス'},
{code: 'KR', name_en: 'Korea, Republic Of', name_ja: '韓国'},
{code: 'KW', name_en: 'Kuwait', name_ja: 'クウェート'},
{code: 'KY', name_en: 'Cayman Islands', name_ja: 'ケイマン諸島'},
{code: 'KZ', name_en: 'Kazakstan', name_ja: 'カザフスタン'},
{code: 'LA', name_en: 'Lao, People\'s Democratic Republic', name_ja: 'ラオス人民民主共和国'},
{code: 'LB', name_en: 'Lebanon', name_ja: 'レバノン'},
{code: 'LC', name_en: 'St. Lucia', name_ja: 'セントルシア'},
{code: 'LK', name_en: 'Sri Lanka', name_ja: 'スリランカ'},
{code: 'LR', name_en: 'Liberia', name_ja: 'リベリア'},
{code: 'LT', name_en: 'Lithuania', name_ja: 'リトアニア'},
{code: 'LU', name_en: 'Luxembourg', name_ja: 'ルクセンブルク'},
{code: 'LV', name_en: 'Latvia', name_ja: 'ラトビア'},
{code: 'MD', name_en: 'Moldova', name_ja: 'モルドバ'},
{code: 'MG', name_en: 'Madagascar', name_ja: 'マダガスカル'},
{code: 'MK', name_en: 'Macedonia', name_ja: 'マケドニア'},
{code: 'ML', name_en: 'Mali', name_ja: 'マリ'},
{code: 'MN', name_en: 'Mongolia', name_ja: 'モンゴル'},
{code: 'MO', name_en: 'Macau', name_ja: 'マカオ'},
{code: 'MR', name_en: 'Mauritania', name_ja: 'モーリタニア'},
{code: 'MS', name_en: 'Montserrat', name_ja: 'モントセラト'},
{code: 'MT', name_en: 'Malta', name_ja: 'マルタ'},
{code: 'MU', name_en: 'Mauritius', name_ja: 'モーリシャス'},
{code: 'MW', name_en: 'Malawi', name_ja: 'マラウイ'},
{code: 'MX', name_en: 'Mexico', name_ja: 'メキシコ'},
{code: 'MY', name_en: 'Malaysia', name_ja: 'マレーシア'},
{code: 'MZ', name_en: 'Mozambique', name_ja: 'モザンビーク'},
{code: 'NA', name_en: 'Namibia', name_ja: 'ナミビア'},
{code: 'NE', name_en: 'Niger', name_ja: 'ナイジャ'},
{code: 'NG', name_en: 'Nigeria', name_ja: 'ナイジェリア'},
{code: 'NI', name_en: 'Nicaragua', name_ja: 'ニカラグア'},
{code: 'NL', name_en: 'Netherlands', name_ja: 'オランダ'},
{code: 'NO', name_en: 'Norway', name_ja: 'ノルウェー'},
{code: 'NP', name_en: 'Nepal', name_ja: 'ネパール'},
{code: 'NZ', name_en: 'New Zealand', name_ja: 'ニュージーランド'},
{code: 'OM', name_en: 'Oman', name_ja: 'オマーン'},
{code: 'PA', name_en: 'Panama', name_ja: 'パナマ'},
{code: 'PE', name_en: 'Peru', name_ja: 'ペルー'},
{code: 'PG', name_en: 'Papua New Guinea', name_ja: 'パプアニューギニア'},
{code: 'PH', name_en: 'Philippines', name_ja: 'フィリピン'},
{code: 'PK', name_en: 'Pakistan', name_ja: 'パキスタン'},
{code: 'PL', name_en: 'Poland', name_ja: 'ポーランド'},
{code: 'PT', name_en: 'Portugal', name_ja: 'ポルトガル'},
{code: 'PW', name_en: 'Palau', name_ja: 'パラオ'},
{code: 'PY', name_en: 'Paraguay', name_ja: 'パラグアイ'},
{code: 'QA', name_en: 'Qatar', name_ja: 'カタール'},
{code: 'RO', name_en: 'Romania', name_ja: 'ルーマニア'},
{code: 'RU', name_en: 'Russia', name_ja: 'ロシア'},
{code: 'SA', name_en: 'Saudi Arabia', name_ja: 'サウジアラビア'},
{code: 'SB', name_en: 'Solomon Islands', name_ja: 'ソロモン諸島'},
{code: 'SC', name_en: 'Seychelles', name_ja: 'セーシェル'},
{code: 'SE', name_en: 'Sweden', name_ja: 'スウェーデン'},
{code: 'SG', name_en: 'Singapore', name_ja: 'シンガポール'},
{code: 'SI', name_en: 'Slovenia', name_ja: 'スロベニア'},
{code: 'SK', name_en: 'Slovakia', name_ja: 'スロバキア'},
{code: 'SL', name_en: 'Sierra Leone', name_ja: 'シエラレオネ'},
{code: 'SN', name_en: 'Senegal', name_ja: 'セネガル'},
{code: 'SR', name_en: 'Suriname', name_ja: 'スリナム'},
{code: 'ST', name_en: 'São Tomé and Príncipe', name_ja: 'サントメプリンシペ'},
{code: 'SV', name_en: 'El Salvador', name_ja: 'エルサルバドル'},
{code: 'SZ', name_en: 'Swaziland', name_ja: 'スワジランド'},
{code: 'TC', name_en: 'Turks and Caicos', name_ja: 'Turks and Caicos'},
{code: 'TD', name_en: 'Chad', name_ja: 'チャド'},
{code: 'TH', name_en: 'Thailand', name_ja: 'タイ'},
{code: 'TJ', name_en: 'Tajikistan', name_ja: 'タジキスタン'},
{code: 'TM', name_en: 'Turkmenistan', name_ja: 'トルクメニスタン'},
{code: 'TN', name_en: 'Tunisia', name_ja: 'チュニジア'},
{code: 'TR', name_en: 'Turkey', name_ja: 'トルコ'},
{code: 'TT', name_en: 'Trinidad and Tobago', name_ja: 'トリニダード・トバゴ'},
{code: 'TW', name_en: 'Taiwan', name_ja: '台湾'},
{code: 'TZ', name_en: 'Tanzania', name_ja: 'タンザニア'},
{code: 'UA', name_en: 'Ukraine', name_ja: 'ウクライナ'},
{code: 'UG', name_en: 'Uganda', name_ja: 'ウガンダ'},
{code: 'US', name_en: 'United States', name_ja: 'アメリカ合衆国'},
{code: 'UY', name_en: 'Uruguay', name_ja: 'ウルグアイ'},
{code: 'UZ', name_en: 'Uzbekistan', name_ja: 'ウズベキスタン'},
{code: 'VC', name_en: 'St. Vincent and The Grenadines', name_ja: 'St. Vincent and The Grenadines', },
{code: 'VE', name_en: 'Venezuela', name_ja: 'ベネズエラ'},
{code: 'VG', name_en: 'British Virgin Islands', name_ja: 'イギリス領ヴァージン諸島'},
{code: 'VN', name_en: 'Vietnam', name_ja: 'ベトナム'},
{code: 'YE', name_en: 'Yemen', name_ja: 'イエメン'},
{code: 'ZA', name_en: 'South Africa', name_ja: '南アフリカ'},
{code: 'ZW', name_en: 'Zimbabwe', name_ja: 'ジンバブエ'},
])